import merge from 'lodash.merge'
import { darkTheme, Theme } from '@rainbow-me/rainbowkit'

export const haiTheme = merge(darkTheme(), {
    blurs: {
        // modalOverlay: '...',
    },
    colors: {
        accentColor: '#41c1d0',
        // accentColorForeground: '...',
        // actionButtonBorder: '...',
        // actionButtonBorderMobile: '...',
        // actionButtonSecondaryBackground: '...',
        // closeButton: '...',
        // closeButtonBackground: '...',
        connectButtonBackground: '#05284c',
        // connectButtonBackgroundError: '...',
        // connectButtonInnerBackground: '...',
        // connectButtonText: '...',
        // connectButtonTextError: '...',
        // connectionIndicator: '...',
        // downloadBottomCardBackground: '...',
        // downloadTopCardBackground: '...',
        // error: '...',
        // generalBorder: '...',
        // generalBorderDim: '...',
        // menuItemBackground: '...',
        // modalBackdrop: '...',
        modalBackground: '#05284c',
        // modalBorder: '...',
        // modalText: '...',
        // modalTextDim: '...',
        // modalTextSecondary: '...',
        // profileAction: '...',
        // profileActionHover: '...',
        // profileForeground: '...',
        // selectedOptionBorder: '...',
        // standby: '...',
    },
    fonts: {
        // body: '...',
    },
    radii: {
        // actionButton: '100%',
        connectButton: '50px',
        // menuButton: '...',
        // modal: '...',
        // modalMobile: '...',
    },
    shadows: {
        // connectButton: '...',
        // dialog: '...',
        // profileDetailsAction: '...',
        // selectedOption: '...',
        // selectedWallet: '...',
        // walletLogo: '...',
    },
} as Theme)